# NumPy. n-dimensional arrays and linear algebra

. Documentation: www.numpy.org/devdocs/reference/index.html

. ndarray data type: www.numpy.org/doc/stable/reference/arrays.ndarray.html

. indexing: www.numpy.org/doc/stable/user/basics.indexing.html#basics-indexing

In [2]:
import numpy as np

In [4]:
data_list_int = [1,2,3,4]

data_arr = np.array(data_list_int)

print(data_arr)
print("Shape: ", data_arr.shape)
print("Number of Dimensions: ", data_arr.ndim) # to check the dimension 
print("Data type: ", data_arr.dtype)
#?

[1 2 3 4]
Shape:  (4,)
Number of Dimensions:  1
Data type:  int32

Note, above, the shape returns "4,". The comma is because it is only row, and no column. This is also seen as it is one dimension.

In [7]:
data_list_mix = [
    [1,2,3,4],
    [False, True, 9.7, 1.3e+1], 
]

data_arr = np.array(data_list_mix)

print(data_arr)
print("Shape: ", data_arr.shape)
print("Number of Dimensions: ", data_arr.ndim)
print("Data type: ", data_arr.dtype)

[[ 1.   2.   3.   4. ]
 [ 0.   1.   9.7 13. ]]
Shape:  (2, 4)
Number of Dimensions:  2
Data type:  float64

Note the answer above
The shape returns 2,4. meaning there are two dimensions. Two rows and four columns. The "False" is no 0, and "True" is now 1
Because it is numpy, and not just list, it is able to convert int/str to float. Try data_list_mix = [
    [1,2,3,4],
    [False, True, 9.7, 1.3e+1], 
] without numpy. it will show it differently

In [10]:
#Arithmetic operations 

print("Sum:", np.sum(data_arr)) #There are multiple arguments that can be added to these lines for specificity
print("Cumsum:\n", np.cumsum(data_arr, axis =0))
print("Mean:", np.mean(data_arr))
print("Std.dev.:", np.round(np.std(data_arr), decimals = 3))
print("Max:", np.max(data_arr, axis = 0))

Sum: 33.7
Cumsum:
 [[ 1.   2.   3.   4. ]
 [ 1.   3.  12.7 17. ]]
Mean: 4.2125
Std.dev.: 4.361
Max: [ 1.   2.   9.7 13. ]

In [14]:
# Indexing 
print(data_arr[1:-1, 1:4])
print(data_arr[:, 0])
print(data_arr[..., 0]) # select all data This is the ellipsis operator. 
#In NumPy, it's a powerful way to select all elements along specific dimensions.

#[..., 0]: ... selects all elements along all dimensions except the last one. [0] then selects the element at index 0 from the last dimension.

sel = data_arr > 5 # select all data arrays greater than 5
print (sel)
print(data_arr[sel]) #?

[]
[1. 0.]
[1. 0.]
[[False False False False]
 [False False  True  True]]
[ 9.7 13. ]

In [16]:
import numpy as np

# Create a 3D array
data_arrs = np.array([[[1, 2, 3], [4, 5, 6]], 
                    [[7, 8, 9], [10, 11, 12]]])

print(data_arrs) 
# Output:
# [[[ 1  2  3]
#   [ 4  5  6]]

#  [[ 7  8  9]
#   [10 11 12]]]

print(data_arrs[..., 0]) 
# Output:
# [[[ 1]
#   [ 4]]

#  [[ 7]
#   [10]]]
#In this example, data_arr[..., 0] selects the first element (at index 0) from each of the inner arrays, effectively extracting the "first slice" along the last dimension

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  4]
 [ 7 10]]

In [20]:
# Adding and removing dimensions
print(data_arr.shape)
ext_arr = data_arr[np.newaxis, ...] #Add a new dimension to an array using np.newaxis.
print(ext_arr.shape)
squ_arr = np.squeeze(ext_arr, axis = 0) # `np.squeeze()` removes dimensions of size 1 from an array.
#axis=0 specifies that the function should remove the dimension at axis 0 (the first dimension).
print(squ_arr.shape)

(2, 4)
(1, 2, 4)
(2, 4)

In [22]:
# Stacking

arrays = [data_arr, 
          np.remainder(data_arr, 2), 
          data_arr + 10]
data_stack = np.stack(arrays, axis = 0)

print(data_stack.shape)
print(data_stack.ndim)
print(data_stack)

(3, 2, 4)
3
[[[ 1.   2.   3.   4. ]
  [ 0.   1.   9.7 13. ]]

 [[ 1.   0.   1.   0. ]
  [ 0.   1.   1.7  1. ]]

 [[11.  12.  13.  14. ]
  [10.  11.  19.7 23. ]]]

# Pandas

##### describe, groupby, concat, merge, join, melt, pivot, stack, unstack.

. Quick start www.pandas.pydata.org/docs/users_guige/10min.html

. DataFrame, Series, etc data structures: www.pandas.pydata.org/docs/users_guide/dsintro.html

In [28]:
import pandas as pd

In [64]:
#Create dataframe from dict

dict_part0 = {
    "PAT": ["424874", "7CD6F7", "A6B1E1", "E47A05"],
    "AGE": [23, 15, 67, 35],
    "SEX": ["MALE", "FEMALE", None, 'fem.'], 
    "CITY": ["Oulu", "Kuopio", "Espoo", "Oulu"]
}

df_part0 = pd.DataFrame.from_dict(dict_part0)

print(df_part0)
print(type(df_part0))
df_part0.head()

      PAT  AGE     SEX    CITY
0  424874   23    MALE    Oulu
1  7CD6F7   15  FEMALE  Kuopio
2  A6B1E1   67    None   Espoo
3  E47A05   35    fem.    Oulu
<class 'pandas.core.frame.DataFrame'>

      PAT  AGE     SEX    CITY
0  424874   23    MALE    Oulu
1  7CD6F7   15  FEMALE  Kuopio
2  A6B1E1   67    None   Espoo
3  E47A05   35    fem.    Oulu

In [86]:
# Create dataframe from records

records_part1 = [
    ('7CD6F7', 16, 'FEMALE', 'OULU', 159),
    ('CACFD6', 18, 'FEMALE', 'KAJAANI', 172),
    ('D6E5E3', 44, 'MALE', 'HELSINKI', 183),
    ('F0982A', 16, 'MALE', 'KEMPELE', 179)
]

df_part1 = pd.DataFrame.from_records(records_part1, 
                                     columns = ["patient_id", "age", "sex", "area", "height_cm"])

print(df_part1)
print(type(df_part1))
df_part1.head()

  patient_id  age     sex      area  height_cm
0     7CD6F7   16  FEMALE      OULU        159
1     CACFD6   18  FEMALE   KAJAANI        172
2     D6E5E3   44    MALE  HELSINKI        183
3     F0982A   16    MALE   KEMPELE        179
<class 'pandas.core.frame.DataFrame'>

  patient_id  age     sex      area  height_cm
0     7CD6F7   16  FEMALE      OULU        159
1     CACFD6   18  FEMALE   KAJAANI        172
2     D6E5E3   44    MALE  HELSINKI        183
3     F0982A   16    MALE   KEMPELE        179

In [68]:
display(df_part0)
df_part0 = df_part0.rename(columns = {"PAT": "patient_id", "AGE":"age", 
                                      "SEX":"sex","CITY":"area"})
display(df_part0)

      PAT  AGE     SEX    CITY
0  424874   23    MALE    Oulu
1  7CD6F7   15  FEMALE  Kuopio
2  A6B1E1   67    None   Espoo
3  E47A05   35    fem.    Oulu

  patient_id  age     sex    area
0     424874   23    MALE    Oulu
1     7CD6F7   15  FEMALE  Kuopio
2     A6B1E1   67    None   Espoo
3     E47A05   35    fem.    Oulu

In [72]:
#Indexing

print(df_part0.loc[2, ["patient_id", "area"]]) # select row labeled 2, and pass the column name patient and area
print("")
print(df_part0.iloc[0:3, [0, 2]]) # index from row 0, stop at 2 ( row 3 won't be included), and then column 0 and 2

patient_id    A6B1E1
area           Espoo
Name: 2, dtype: object

  patient_id     sex
0     424874    MALE
1     7CD6F7  FEMALE
2     A6B1E1    None

In [74]:
# Series

print(df_part0["patient_id"])
print(type(df_part0["patient_id"]))

0    424874
1    7CD6F7
2    A6B1E1
3    E47A05
Name: patient_id, dtype: object
<class 'pandas.core.series.Series'>

In [76]:
df_tmp = df_part0.loc[df_part0["area"] == "Oulu", :]

print(df_tmp)# print only patients from oulu

  patient_id  age   sex  area
0     424874   23  MALE  Oulu
3     E47A05   35  fem.  Oulu

In [78]:
# fill missing variable 

df_part0 = df_part0.fillna(value = {"sex": "male"})
print(df_part0)

  patient_id  age     sex    area
0     424874   23    MALE    Oulu
1     7CD6F7   15  FEMALE  Kuopio
2     A6B1E1   67    male   Espoo
3     E47A05   35    fem.    Oulu

In [80]:
# Standardize and correct typo

df_part0 = df_part0.replace(to_replace = {"sex": "fem."}, value = "female")
print(df_part0)

  patient_id  age     sex    area
0     424874   23    MALE    Oulu
1     7CD6F7   15  FEMALE  Kuopio
2     A6B1E1   67    male   Espoo
3     E47A05   35  female    Oulu

In [82]:
# Concatenate

df_full = pd.concat([df_part0, df_part1], axis = 0)
print(df_full, end = "\n\n")

  patient_id  age     sex    area  location  height_cm
0     424874   23    MALE    Oulu       NaN        NaN
1     7CD6F7   15  FEMALE  Kuopio       NaN        NaN
2     A6B1E1   67    male   Espoo       NaN        NaN
3     E47A05   35  female    Oulu       NaN        NaN
0     7CD6F7   16  FEMALE     NaN      OULU      159.0
1     CACFD6   18  FEMALE     NaN   KAJAANI      172.0
2     D6E5E3   44    MALE     NaN  HELSINKI      183.0
3     F0982A   16    MALE     NaN   KEMPELE      179.0

In [88]:
# Merge, Join, or Concatenate 

for kind in ("inner", "left", "outer"): 
    df_merge = df_part0.merge(df_part1, on = ["patient_id", "age", "sex", "area"], how = kind)
    print(kind, "\n", df_merge, end="\n\n")

inner
 Empty DataFrame
Columns: [patient_id, age, sex, area, height_cm]
Index: []

left
   patient_id  age     sex    area  height_cm
0     424874   23    MALE    Oulu        NaN
1     7CD6F7   15  FEMALE  Kuopio        NaN
2     A6B1E1   67    male   Espoo        NaN
3     E47A05   35  female    Oulu        NaN

outer
   patient_id  age     sex      area  height_cm
0     424874   23    MALE      Oulu        NaN
1     7CD6F7   15  FEMALE    Kuopio        NaN
2     7CD6F7   16  FEMALE      OULU      159.0
3     A6B1E1   67    male     Espoo        NaN
4     CACFD6   18  FEMALE   KAJAANI      172.0
5     D6E5E3   44    MALE  HELSINKI      183.0
6     E47A05   35  female      Oulu        NaN
7     F0982A   16    MALE   KEMPELE      179.0

In [94]:
#Remove duplicated records

df_merge = df_merge.drop_duplicates(subset = ["patient_id", ], keep = "last")
print(df_merge)

  patient_id  age     sex      area  height_cm
0     424874   23    MALE      Oulu        NaN
2     7CD6F7   16  FEMALE      OULU      159.0
3     A6B1E1   67    male     Espoo        NaN
4     CACFD6   18  FEMALE   KAJAANI      172.0
5     D6E5E3   44    MALE  HELSINKI      183.0
6     E47A05   35  female      Oulu        NaN
7     F0982A   16    MALE   KEMPELE      179.0

In [102]:
df_pivot = df_merge.pivot(values = ["height_cm", "age"], columns = ["area", "sex"], index = "patient_id")
display(df_pivot)
df_pivot_table = df_merge.pivot_table(values = ["height_cm", "age"], columns = ["area", "sex"], aggfunc = "mean")
display(df_pivot_table)

           height_cm                                                age  \
area            Oulu   OULU Espoo KAJAANI HELSINKI   Oulu KEMPELE  Oulu
sex             MALE FEMALE  male  FEMALE     MALE female    MALE  MALE
patient_id
424874           NaN    NaN   NaN     NaN      NaN    NaN     NaN  23.0
7CD6F7           NaN  159.0   NaN     NaN      NaN    NaN     NaN   NaN
A6B1E1           NaN    NaN   NaN     NaN      NaN    NaN     NaN   NaN
CACFD6           NaN    NaN   NaN   172.0      NaN    NaN     NaN   NaN
D6E5E3           NaN    NaN   NaN     NaN    183.0    NaN     NaN   NaN
E47A05           NaN    NaN   NaN     NaN      NaN    NaN     NaN   NaN
F0982A           NaN    NaN   NaN     NaN      NaN    NaN   179.0   NaN


area         OULU Espoo KAJAANI HELSINKI   Oulu KEMPELE
sex        FEMALE  male  FEMALE     MALE female    MALE
patient_id
424874        NaN   NaN     NaN      NaN    NaN     NaN
7CD6F7       16.0   NaN     NaN      NaN    NaN     NaN
A6B1E1        NaN  67.0     NaN      NaN    NaN     NaN
CACFD6        NaN   NaN    18.0      NaN    NaN     NaN
D6E5E3        NaN   NaN     NaN     44.0    NaN     NaN
E47A05        NaN   NaN     NaN      NaN   35.0     NaN
F0982A        NaN   NaN     NaN      NaN    NaN    16.0

area      Espoo HELSINKI KAJAANI KEMPELE   OULU  Oulu
sex        male     MALE  FEMALE    MALE FEMALE  MALE female
age        67.0     44.0    18.0    16.0   16.0  23.0   35.0
height_cm   NaN    183.0   172.0   179.0  159.0   NaN    NaN

In [104]:
df_pivot_table.melt()

        area     sex  value
0      Espoo    male   67.0
1      Espoo    male    NaN
2   HELSINKI    MALE   44.0
3   HELSINKI    MALE  183.0
4    KAJAANI  FEMALE   18.0
5    KAJAANI  FEMALE  172.0
6    KEMPELE    MALE   16.0
7    KEMPELE    MALE  179.0
8       OULU  FEMALE   16.0
9       OULU  FEMALE  159.0
10      Oulu    MALE   23.0
11      Oulu    MALE    NaN
12      Oulu  female   35.0
13      Oulu  female    NaN

# SciPy, Matlab, statsmodels, scikit-learn

# Modeling

In [226]:
import sklearn 
from sklearn.datasets import make_classification

#generate data 
def create_dataset(n_samples = 1000):
    #Generate features and targets 
    X, y = make_classification(
        n_samples=n_samples, 
        n_features=3, 
        n_informative=3, 
        n_redundant = 0, 
        random_state = 42
    )
    X_cont = X[:, :2]
    X_cont[:, 0] = np.round((X_cont[:, 0] - np.min(X_cont[:,0]))/np.ptp(X_cont[:,0]) * 60.)  #age age[0:60]
    X_rand = np.random.uniform(size = (1000, 1))
    X_cat = np.asarray(["male" if e >= 0.0 else "female" for e in X[:,2]])[..., None] # sex [male/female]
    
    #Combine features into DataFrame
    X = pd.DataFrame(
        np.hstack([X_cont, X_rand, X_cat]),
        columns = ["age", "biomaker", "randoms", "sex"], 
    )
    y = pd.Series(y, name = "diagnosis")
    return X, y

#Create dataset 
X, y = create_dataset() 

numeric_features = ["age", "biomaker", "randoms"]
categorical_features = ["sex"]

In [228]:
df = X.assign(diagnosis=y)
display(df)

      age              biomaker               randoms     sex  diagnosis
0    39.0    0.7268569713619627    0.8998584205539687    male          1
1    26.0   -0.7498603949848086    0.7686804075303587  female          0
2    18.0   -1.0321714064274123    0.9607908957454427    male          0
3    40.0   -0.8662834645469855    0.9731977061774096  female          0
4    44.0    1.6413878150791246    0.8534880473860904    male          1
..    ...                   ...                   ...     ...        ...
995  20.0   -0.4740206333031428     0.902199611411366  female          0
996  26.0    -1.354977768451978  0.008331519265319165    male          0
997  17.0  -0.27580521185662465   0.30918416985460984  female          0
998  24.0   -0.9095859274094646     0.683370779091237    male          0
999  43.0    0.9701803839011408    0.1889415942995064    male          1

[1000 rows x 5 columns]

# 3.1 statsmodel. Statistical  modeling and hypothesis testing

In [190]:
import statsmodels.api as sm 
from statsmodels.formula.api import logit

In [192]:
print(df.dtypes)

age          object
biomaker     object
randoms      object
sex          object
diagnosis     int32
dtype: object

In [194]:
# convert variable types 

df["age"] = pd.to_numeric(df["age"])
df["biomaker"] = pd.to_numeric(df["biomaker"])
df["randoms"] = pd.to_numeric(df["randoms"]) 
df["sex"] = df["sex"].astype('category') 

print(df.dtypes)

age           float64
biomaker      float64
randoms       float64
sex          category
diagnosis       int32
dtype: object

In [196]:
# build a model (LOGISTIC REGRESSION)

formula = "diagnosis ~ age + biomaker + randoms + C(sex)" 
model_sm = logit(formula, df) 
results = model_sm.fit()

Optimization terminated successfully.
         Current function value: 0.201700
         Iterations 9

In [198]:
print(results.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:              diagnosis   No. Observations:                 1000
Model:                          Logit   Df Residuals:                      995
Method:                           MLE   Df Model:                            4
Date:                Tue, 28 Jan 2025   Pseudo R-squ.:                  0.7090
Time:                        17:16:05   Log-Likelihood:                -201.70
converged:                       True   LL-Null:                       -693.15
Covariance Type:            nonrobust   LLR p-value:                1.822e-211
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        -14.7739      1.221    -12.097      0.000     -17.168     -12.380
C(sex)[T.male]     1.1323      0.357      3.170      0.002       0.432       1.832
age                0.4105      0.031     13.191      0.000       0.350       0.472
biomaker           0.7452      0.133      5.590      0.000       0.484       1.007
randoms           -0.2160      0.446     -0.484      0.628      -1.090       0.658
==================================================================================

# 3.2 Scikit_Learn. Machine learning 

www.scikit-learn.org/stable/getting_started.html 

www.scikit-learn.org/stable/user_guide.html

In [200]:
import sklearn 
from sklearn.datasets import make_classification 
from sklearn.model_selection import train_test_split, cross_val_score 
from sklearn.preprocessing import StandardScaler, OneHotEncoder 
from sklearn.compose import ColumnTransformer 
from sklearn.pipeline import Pipeline 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import classification_report 
import matplotlib.pyplot as plt

In [230]:
# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Define preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[ 
        ("num", StandardScaler(), numeric_features), 
        ("cat", OneHotEncoder(drop='first'), categorical_features) 
    ]) 

# Define model to try
model = LogisticRegression(random_state=42, penalty=None)

In [232]:
print(X_train.columns)

Index(['age', 'biomaker', 'randoms', 'sex'], dtype='object')

In [234]:
print(X_train.dtypes)

age         object
biomaker    object
randoms     object
sex         object
dtype: object

In [236]:
# Train Model

# Create Pipeline
pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", model)
])

# Perform Cross-Validation
#cv_scores = cross_val_score(pipeline, X_train, y_train, 
                            #cv=5, scoring ="accuracy")
#print("Cross-Validation Scores:", cv_scores)  # Print the scores

# Fit the model on full training data (after CV)
#pipeline.fit(X_train, y_train)

In [242]:
# Train Model 

# Create Pipeline 

# pipeline = Pipeline([
#     ("preprocessor", preprocessor), 
#     ("classifier", model)
# ])

# Perform cross validation 

cv_scores = cross_val_score(pipeline, X_train, y_train, 
                            cv = 5, scoring = "accuracy") 

#fit the model on full training data

pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'biomaker',
                                                   'randoms']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['sex'])])),
                ('classifier',
                 LogisticRegression(penalty=None, random_state=42))])

In [244]:
# Evaluate the model 

# Get test set predictions 
y_pred = pipeline.predict(X_test)
print(f"Predictions: {y_pred}")

Predictions: [1 1 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 1 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 0 0 0 1 0 1
 0 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 0 1 1 0 0 1 0
 0 0 0 1 0 1 1 1 0 0 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 1 0
 1 0 0 1 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 1 1 0 1 0 1 0
 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1]

In [246]:
# Store report 
test_report = classification_report(y_test, y_pred)

In [248]:
print("Cross-validation scores:") 
print(f"{cv_scores.mean():.3f} (+/- {cv_scores.std() * 2:.3f})")

print("\nTest set performance") 
print(test_report)

Cross-validation scores:
0.921 (+/- 0.043)

Test set performance
              precision    recall  f1-score   support

           0       0.90      0.86      0.88       110
           1       0.84      0.89      0.86        90

    accuracy                           0.88       200
   macro avg       0.87      0.88      0.87       200
weighted avg       0.88      0.88      0.88       200

In [250]:
# Get feature importance 
feature_names = numeric_features + categorical_features 

coef = pipeline.named_steps["classifier"].coef_[0]
feature_importance = dict(zip(feature_names, coef))
print(f"features importances: {feature_importance}")

features importances: {'age': 4.505302160313943, 'biomaker': 0.9171221510711042, 'randoms': 0.0678528814271021, 'sex': 1.6755199274852552}

# Backends for heavy computations

Numpy vectorisation www.numpy.org/doc/stable/user/basics.broadcasting.html

www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOPerations.html

joblib: www.joblib.readthedocs.io/en/latest/parallel.html

In [ ]:
import time 
import numpy as np

In [ ]:
data = np.random.uniform(low = -1.0, high = 1.0, size = (5000, 5000)

In [ ]:
def fn_for_loop(arr_in):
    i, j, = arr_in.shape
    arr_out = np.zeros_like(arr_in, dtype = int)
    for a in range(i): 
        for b in range(j): 
            if arr_in[a, b] >= 0: 
                arr_out[a, b] = 1
            else:
                arr_out[a, b] = 0
    return arr_out


def fn_vec(arr_in): 
    arr_out = (arr_in >=0.astype(int)
    return arr_out

In [ ]:
t0 = time.time()
res = fn_for_loop(data)
t1 = time.time()
print(f"Time (for loop): {t1 - t0}s")

t0 = time.time()
res = fn_vec(data)
t1 = time.time()
print(f"Time (vectorised): {t1 - t0}s")

# Parallel (multi-core) execution

In [256]:
from joblib import Parallel, delayed

In [258]:
num_samples = 10 
def fn_slow(x):
    time.sleep(1)
    return x**2

In [266]:
# sequential executions/single_core

t0 = time.time()
results = []
for data in range(num_samples): 
    t = fn_slow(data)
    results.append(t)
t1 = time.time()
print(f"Total time: {t1-t0}s")

Total time: 10.005673170089722s

In [268]:
# Paralle execution/multi-core 

jobs = []
for data in range(num_samples):
    t = delayed(fn_slow)(data)
    jobs.append(t)

t0 = time.time()
res = Parallel(n_jobs = 12)(jobs)
t1 = time.time()
print(f"Total time: {t1-t0}s")

Total time: 1.9676344394683838s